import { Role } from './roles';

export const FIRESTORE_SCHEMAS = {
  users: {
    uid: 'string',
    email: 'string',
    displayName: 'string',
    role: 'student | facilitator | super_admin' as Role,
    photoURL: 'string?',
    isActive: 'boolean',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  profiles: {
    uid: 'string',
    bio: 'string?',
    phone: 'string?',
    institution: 'string?',
    avatarUrl: 'string?',
    metadata: 'map?',
    updatedAt: 'timestamp',
  },
  courses: {
    title: 'string',
    description: 'string',
    facilitatorId: 'string',
    isPublished: 'boolean',
    tags: 'string[]',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  enrollments: {
    courseId: 'string',
    studentId: 'string',
    status: 'active | completed | dropped',
    enrolledAt: 'timestamp',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  assignments: {
    courseId: 'string',
    title: 'string',
    description: 'string',
    dueAt: 'timestamp',
    maxScore: 'number',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  submissions: {
    assignmentId: 'string',
    studentId: 'string',
    fileUrl: 'string?',
    content: 'string?',
    score: 'number?',
    feedback: 'string?',
    submittedAt: 'timestamp',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  notifications: {
    userId: 'string',
    title: 'string',
    body: 'string',
    type: 'info | alert | assignment | grade | risk | appointment | work_hours',
    isRead: 'boolean',
    data: 'map?',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  device_tokens: {
    uid: 'string',
    token: 'string',
    platform: 'ios | android | web',
    deploymentTarget: 'string',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  announcements: {
    title: 'string',
    body: 'string',
    authorId: 'string',
    targetRoles: 'string[]',
    isActive: 'boolean',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  audit_logs: {
    actorId: 'string',
    action: 'string',
    resource: 'string',
    resourceId: 'string',
    metadata: 'map?',
    createdAt: 'timestamp',
  },
  risk_alerts: {
    studentId: 'string',
    facilitatorId: 'string',
    severity: 'low | medium | high | critical',
    title: 'string',
    description: 'string',
    status: 'open | acknowledged | resolved',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  appointments: {
    studentId: 'string',
    facilitatorId: 'string',
    scheduledAt: 'timestamp',
    durationMinutes: 'number',
    status: 'scheduled | completed | cancelled',
    notes: 'string?',
    notifyBeforeMinutes: 'number',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  conversations: {
    participantIds: 'string[]',
    lastMessageAt: 'timestamp',
    lastMessagePreview: 'string',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  messages: {
    conversationId: 'string',
    senderId: 'string',
    body: 'string',
    attachmentUrl: 'string?',
    isRead: 'boolean',
    createdAt: 'timestamp',
  },
  work_hours_schedules: {
    facilitatorId: 'string',
    dayOfWeek: 'number',
    startTime: 'string',
    endTime: 'string',
    isActive: 'boolean',
    notifyBeforeMinutes: 'number',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  assessment_templates: {
    title: 'string',
    description: 'string',
    category: 'string',
    version: 'number',
    isActive: 'boolean',
    createdBy: 'string',
    questionCount: 'number',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  assessment_questions: {
    templateId: 'string',
    order: 'number',
    prompt: 'string',
    type: 'short_text | long_text | single_choice | multi_choice | scale_1_5 | scale_1_10 | yes_no',
    options: 'string[]?',
    isRequired: 'boolean',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
  assessments: {
    templateId: 'string',
    studentId: 'string',
    status: 'in_progress | submitted',
    submittedAt: 'timestamp?',
    responseCount: 'number',
    createdAt: 'timestamp',
    updatedAt: 'timestamp',
  },
} as const;
