export const palette = {
  spartanRed: '#DC2626',
  spartanRedDark: '#991B1B',
  spartanGold: '#F59E0B',
  slate900: '#0F172A',
  slate800: '#1E293B',
  slate700: '#334155',
  slate600: '#475569',
  slate500: '#64748B',
  slate400: '#94A3B8',
  slate300: '#CBD5E1',
  slate200: '#E2E8F0',
  slate100: '#F1F5F9',
  slate50: '#F8FAFC',
  white: '#FFFFFF',
  black: '#000000',
  success: '#16A34A',
  warning: '#D97706',
  error: '#DC2626',
  info: '#2563EB',
} as const;

export const lightColors = {
  background: palette.slate50,
  surface: palette.white,
  surfaceElevated: palette.white,
  text: palette.slate900,
  textSecondary: palette.slate600,
  textMuted: palette.slate400,
  border: palette.slate200,
  primary: palette.spartanRed,
  primaryDark: palette.spartanRedDark,
  accent: palette.spartanGold,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  info: palette.info,
  tabBar: palette.white,
  tabBarBorder: palette.slate200,
  // Semantic state backgrounds & borders
  errorBackground: '#FEE2E2',
  errorBorder: '#FECACA',
  errorText: '#B91C1C',
  errorLightBackground: '#FEF2F2',
  successBackground: '#DCFCE7',
  successText: palette.success,
  warningBackground: '#FEF3C7',
  warningBorder: '#FCD34D',
  warningText: '#92400E',
  infoBackground: '#EEF2FF',
  infoBorder: '#C7D2FE',
  infoText: '#3730A3',
  infoBadgeText: '#4338CA',
  neutralBackground: palette.slate100,
  criticalBackground: '#FEF2F2',
  criticalBorder: '#FECACA',
  criticalText: palette.spartanRedDark,
  moderateBackground: '#FFEDD5',
  moderateText: '#EA580C',
} as const;

export const darkColors = {
  background: palette.slate900,
  surface: palette.slate800,
  surfaceElevated: palette.slate700,
  text: palette.slate50,
  textSecondary: palette.slate300,
  textMuted: palette.slate500,
  border: palette.slate700,
  primary: palette.spartanRed,
  primaryDark: palette.spartanRedDark,
  accent: palette.spartanGold,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  info: palette.info,
  tabBar: palette.slate800,
  tabBarBorder: palette.slate700,
  // Semantic state backgrounds & borders
  errorBackground: '#7F1D1D',
  errorBorder: palette.spartanRedDark,
  errorText: '#FCA5A5',
  errorLightBackground: '#450A0A',
  successBackground: '#052E16',
  successText: '#86EFAC',
  warningBackground: '#451A03',
  warningBorder: '#78350F',
  warningText: '#FDE68A',
  infoBackground: '#172554',
  infoBorder: '#1E3A5F',
  infoText: '#93C5FD',
  infoBadgeText: '#93C5FD',
  neutralBackground: palette.slate700,
  criticalBackground: '#450A0A',
  criticalBorder: palette.spartanRedDark,
  criticalText: '#FCA5A5',
  moderateBackground: '#431407',
  moderateText: '#FDBA74',
} as const;

export type ColorScheme = typeof lightColors;
