export const palette = {
  spartanRed: '#DC2626',
  spartanRedDark: '#991B1B',
  spartanGold: '#F59E0B',
  slate900: '#0F172A',
  slate800: '#1E293B',
  slate700: '#334155',
  slate600: '#475569',
  slate500: '#64748B',
  slate400: '#94A3B8',
  slate300: '#CBD5E1',
  slate200: '#E2E8F0',
  slate100: '#F1F5F9',
  slate50: '#F8FAFC',
  white: '#FFFFFF',
  black: '#000000',
  success: '#16A34A',
  warning: '#D97706',
  error: '#DC2626',
  info: '#2563EB',
} as const;

export const lightColors = {
  background: palette.slate50,
  surface: palette.white,
  surfaceElevated: palette.white,
  text: palette.slate900,
  textSecondary: palette.slate600,
  textMuted: palette.slate400,
  border: palette.slate200,
  primary: palette.spartanRed,
  primaryDark: palette.spartanRedDark,
  accent: palette.spartanGold,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  info: palette.info,
  tabBar: palette.white,
  tabBarBorder: palette.slate200,
} as const;

export const darkColors = {
  background: palette.slate900,
  surface: palette.slate800,
  surfaceElevated: palette.slate700,
  text: palette.slate50,
  textSecondary: palette.slate300,
  textMuted: palette.slate500,
  border: palette.slate700,
  primary: palette.spartanRed,
  primaryDark: palette.spartanRedDark,
  accent: palette.spartanGold,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  info: palette.info,
  tabBar: palette.slate800,
  tabBarBorder: palette.slate700,
} as const;

export type ColorScheme = typeof lightColors;
